### ISSUE TITLE
You are missing the Lean Wolf Steak towards the Horde War Effort

### ISSUE THREAD

**Issue by oskarwiskman** [cholewa1992/Tuck#6]
The full list of needed items :)
10,000  Lean Wolf Steak
17,000  Spotted Yellowtail
10,000  Baked Salmon
250,000  Wool Bandage
250,000  Mageweave Bandage
400,000  Runecloth Bandage
96,000  Peacebloom
19,000  Firebloom
26,000  Purple Lotus
90,000  Copper Bar
22,000  Tin Bar
18,000  Mithril Bar
60,000  Heavy Leather
80,000  Thick Leather
60,000  Rugged Leather

**Comment by cnettelblad** [comment]
Since the War Effort logic has been removed from the bot already, I'll go ahead and close this issue :)
